title: אלכס פולונסקי
description: בדיקה בדיקה בדיקה בדיקה
baseurl: "/notes"

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics:
disqus_shortname:
